name: E2E Tests

on: [push]

env:
  CHROMEDRIVER_FILEPATH: /usr/local/share/chrome_driver/chromedriver

jobs:

  build:
    name: E2E Tests
    runs-on: self-hosted
    container:
      image: public.ecr.aws/cypress-io/cypress/browsers:node14.16.0-chrome89-ff77
      options: -u 1001:1001 -v /usr/local/share:/share
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        ci_node_total: [8]
        ci_node_index: [1, 2, 3, 4, 5, 6, 7, 8]
    defaults:
      run:
        working-directory: content-build

    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/VA-Internal-S2-RCA1-v1.cer.pem
      CHROMEDRIVER_FILEPATH: /share/chrome_driver/chromedriver

    steps:
      - name: Checkout vagov-content
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/vagov-content
          path: vagov-content

      - name: Checkout content-build
        uses: actions/checkout@v2
        with:
          path: content-build

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ steps.get-node-version.outputs.NODE_VERSION }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          command: yarn install --frozen-lockfile --prefer-offline --production=false
          max_attempts: 3
          timeout_minutes: 5
        env:
          YARN_CACHE_FOLDER: .cache/yarn

      - name: Build
        run: yarn build --buildtype=vagovprod --asset-source=local --drupal-address=https://cms-vets-website-branch-builds-lo9uhqj18nwixunsjadvjsynuni7kk1u.ci.cms.va.gov --pull-drupal --drupal-max-parallel-requests=15 --no-drupal-proxy --verbose
        timeout-minutes: 60
        env:
          NODE_ENV: production

      # - name: Run Nightwatch E2E Tests
      #   run: yarn test:e2e
      #   timeout-minutes: 20
      #   env:
      #     BUILDTYPE: vagovprod

      - name: Start content-build
        run: node src/platform/testing/e2e/test-server.js --buildtype vagovprod --port=3002 &

      - name: Run Cypress E2E Tests
        run: CYPRESS_CONTENT_BUILD_PORT=$CONTENT_BUILD_PORT yarn cy:run --port 3001 --config baseUrl=http://localhost:3002--reporter cypress-multi-reporters --reporter-options "configFile=config/cypress-reporters.json" --spec "src/platform/site-wide/tests/sitemap/sitemap-${{ matrix.ci_node_index }}.cypress.spec.js"

      # - name: Publish test results
      #   if: ${{ always() }}
      #   uses: mikepenz/action-junit-report@v2.4.2
      #   with:
      #     check_name: 'Cypress Tests Summary'
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     report_paths: 'test-results/e2e-test-output-*.xml'

      # - name: Archive Cypress test videos
      #   uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: cypress-video-artifacts
      #     path: cypress/videos

      # - name: Archive Cypress test screenshots
      #   uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: cypress-screenshot-artifacts
      #     path: cypress/screenshots
