name: E2E Tests

on: [push]

env:
  CHROMEDRIVER_FILEPATH: /usr/local/share/chrome_driver/chromedriver

jobs:
  build:
    name: Build
    runs-on: [self-hosted, asg]
    timeout-minutes: 120

    defaults:
      run:
        working-directory: content-build

    env:
      DRUPAL_ADDRESS: https://cms-vets-website-branch-builds-lo9uhqj18nwixunsjadvjsynuni7kk1u.ci.cms.va.gov
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/VA-Internal-S2-RCA1-v1.cer.pem

    steps:
      - name: Checkout vagov-content
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/vagov-content
          path: vagov-content

      - name: Checkout content-build
        uses: actions/checkout@v2
        with:
          path: content-build

      - name: Get Node version
        id: get-node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.get-node-version.outputs.NODE_VERSION }}

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ steps.get-node-version.outputs.NODE_VERSION }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline --network-concurrency 1
        env:
          YARN_CACHE_FOLDER: ~/.cache/yarn

      - name: Set Drupal address
        run: echo "DRUPAL_ADDRESS=http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com" >> $GITHUB_ENV

      - name: Build
        run: yarn build --buildtype=vagovprod --asset-source=local --drupal-address=https://cms-vets-website-branch-builds-lo9uhqj18nwixunsjadvjsynuni7kk1u.ci.cms.va.gov --pull-drupal --drupal-max-parallel-requests=15 --no-drupal-proxy --verbose
        env:
          NODE_ENV: production

      - name: Compress E2E test build
        run: tar -C build/vagovprod -cjf test-build.tar.bz2 .

      - name: Upload E2E test build artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-build.tar.bz2
          path: content-build/test-build.tar.bz2
          retention-days: 1
  
  a11y:
    name: E2E Tests
    needs: build
    runs-on: [self-hosted, asg]
    container:
      image: public.ecr.aws/cypress-io/cypress/browsers:node14.16.0-chrome89-ff77
      options: -u 1001:1001 -v /usr/local/share:/share
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        ci_node_total: [8]
        ci_node_index: [1, 2, 3, 4, 5, 6, 7, 8]
    defaults:
      run:
        working-directory: content-build

    env:
      NODE_EXTRA_CA_CERTS: /share/ca-certificates/VA-Internal-S2-RCA1-v1.cer.crt
      CHROMEDRIVER_FILEPATH: /share/chrome_driver/chromedriver

    steps:
      - name: Checkout vagov-content
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/vagov-content
          path: vagov-content

      - name: Checkout content-build
        uses: actions/checkout@v2
        with:
          path: content-build

      - name: Download production build artifact
        uses: actions/download-artifact@v2
        with:
          name: test-build.tar.bz2

      - name: Unpack build
        run: |
          mkdir -p build/vagovprod
          tar -C build/vagovprod -xjf /__w/content-build/content-build/test-build.tar.bz2

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ steps.get-node-version.outputs.NODE_VERSION }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          command: yarn install --frozen-lockfile --prefer-offline --production=false
          max_attempts: 3
          timeout_minutes: 5
        env:
          YARN_CACHE_FOLDER: .cache/yarn

      - name: Start content-build
        run: node src/platform/testing/e2e/test-server.js --buildtype vagovprod --port=3002 &

      - name: Run Cypress E2E Tests
        run: CYPRESS_CONTENT_BUILD_PORT=3002 yarn cy:run --port 3001 --config baseUrl=http://localhost:3002 --reporter cypress-multi-reporters --reporter-options "configFile=config/cypress-reporters.json" --spec "src/platform/site-wide/tests/sitemap/sitemap-${{ matrix.ci_node_index }}.cypress.spec.js"

      # - name: Publish test results
      #   if: ${{ always() }}
      #   uses: mikepenz/action-junit-report@v2.4.2
      #   with:
      #     check_name: 'Cypress Tests Summary'
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     report_paths: 'test-results/e2e-test-output-*.xml'

      # - name: Archive Cypress test videos
      #   uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: cypress-video-artifacts
      #     path: cypress/videos

      # - name: Archive Cypress test screenshots
      #   uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: cypress-screenshot-artifacts
      #     path: cypress/screenshots
